### ISSUE TITLE
StatefulSet Pod in CrashLoop

### ISSUE THREAD

**Issue by poblahblahblah** [SumoLogic/sumologic-kubernetes-collection#3206]
**Describe the bug** A clear and concise description of what the bug is.

One of the pods in the StatefulSet is in a Crashloop - see log for the exact error(s)

**Logs** Logs which can be helpful in investigating the issue.

```
2023-08-11T17:27:38.072Z	info	service/telemetry.go:92	Setting up own telemetry...
2023-08-11T17:27:38.072Z	info	service/telemetry.go:149	Serving Prometheus metrics	{"address": ":8888", "level": "Basic"}
2023-08-11T17:27:38.073Z	info	sumologicexporter@v0.0.0-00010101000000-000000000000/exporter.go:92	Sumo Logic Exporter configured	{"kind": "exporter", "data_type": "logs", "name": "sumologic/systemd", "log_format": "json", "metric_format": "otlp", "trace_format": "otlp"}
2023-08-11T17:27:38.074Z	info	memorylimiterprocessor@v0.76.1/memorylimiter.go:149	Using percentage memory limiter	{"kind": "processor", "name": "memory_limiter", "pipeline": "logs/otlp/kubelet", "total_memory_mib": 2048, "limit_percentage": 75, "spike_limit_percentage": 20}
2023-08-11T17:27:38.074Z	info	memorylimiterprocessor@v0.76.1/memorylimiter.go:113	Memory limiter configured	{"kind": "processor", "name": "memory_limiter", "pipeline": "logs/otlp/kubelet", "limit_mib": 1536, "spike_limit_mib": 409, "check_interval": 5}
2023-08-11T17:27:38.074Z	info	sumologicexporter@v0.0.0-00010101000000-000000000000/exporter.go:92	Sumo Logic Exporter configured	{"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "log_format": "json", "metric_format": "otlp", "trace_format": "otlp"}
2023-08-11T17:27:38.075Z	info	kube/client.go:110	k8s filtering	{"kind": "processor", "name": "k8s_tagger", "pipeline": "logs/otlp/containers", "labelSelector": "", "fieldSelector": ""}
2023-08-11T17:27:38.076Z	info	service/service.go:129	Starting otelcol-sumo...	{"Version": "v0.76.1-sumo-0", "NumCPU": 8}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:41	Starting extensions...
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:44	Extension is starting...	{"kind": "extension", "name": "file_storage"}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:48	Extension started.	{"kind": "extension", "name": "file_storage"}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:44	Extension is starting...	{"kind": "extension", "name": "pprof"}
2023-08-11T17:27:38.076Z	info	pprofextension@v0.76.3/pprofextension.go:71	Starting net/http/pprof server	{"kind": "extension", "name": "pprof", "config": {"TCPAddr":{"Endpoint":"localhost:1777"},"BlockProfileFraction":0,"MutexProfileFraction":0,"SaveToFile":""}}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:48	Extension started.	{"kind": "extension", "name": "pprof"}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:44	Extension is starting...	{"kind": "extension", "name": "health_check"}
2023-08-11T17:27:38.076Z	info	healthcheckextension@v0.76.3/healthcheckextension.go:45	Starting health_check extension	{"kind": "extension", "name": "health_check", "config": {"Endpoint":"0.0.0.0:13133","TLSSetting":null,"CORS":null,"Auth":null,"MaxRequestBodySize":0,"IncludeMetadata":false,"Path":"/","ResponseBody":null,"CheckCollectorPipeline":{"Enabled":false,"Interval":"5m","ExporterFailureThreshold":5}}}
2023-08-11T17:27:38.076Z	warn	internal/warning.go:51	Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks	{"kind": "extension", "name": "health_check", "documentation": "https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks"}
2023-08-11T17:27:38.076Z	info	extensions/extensions.go:48	Extension started.	{"kind": "extension", "name": "health_check"}
2023-08-11T17:27:38.076Z	info	sumologicexporter@v0.0.0-00010101000000-000000000000/exporter.go:470	setting data urls	{"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "logs_url": "SNIP", "metrics_url": "SNIP", "traces_url": "SNIP"}
2023-08-11T17:27:38.078Z	info	internal/persistent_storage.go:300	Fetching items left for dispatch by consumers	{"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "queueName": "sumologic/containers-logs", "numberOfItems": 1}
2023-08-11T17:27:38.078Z	warn	internal/persistent_storage.go:335	Failed unmarshalling item	{"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "queueName": "sumologic/containers-logs", "key": "1069207", "error": "value not set"}
2023-08-11T17:27:38.078Z	error	internal/persistent_storage.go:164	Errors occurred while moving items for dispatching back to queue	{"kind": "exporter", "data_type": "logs", "name": "sumologic/containers", "queueName": "sumologic/containers-logs", "numberOfItems": 1, "errorCount": 1}
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*persistentContiguousStorage).enqueueNotDispatchedReqs
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/internal/persistent_storage.go:164
go.opentelemetry.io/collector/exporter/exporterhelper/internal.newPersistentContiguousStorage
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/internal/persistent_storage.go:110
go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewPersistentQueue
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/internal/persistent_queue.go:53
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).initializePersistentQueue
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:165
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:200
go.opentelemetry.io/collector/exporter/exporterhelper.newBaseExporter.func1
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/common.go:177
go.opentelemetry.io/collector/component.StartFunc.Start
	go.opentelemetry.io/collector/component@v0.76.1/component.go:84
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll
	go.opentelemetry.io/collector@v0.76.1/service/internal/graph/graph.go:295
go.opentelemetry.io/collector/service.(*Service).Start
	go.opentelemetry.io/collector@v0.76.1/service/service.go:138
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents
	go.opentelemetry.io/collector@v0.76.1/otelcol/collector.go:184
go.opentelemetry.io/collector/otelcol.(*Collector).Run
	go.opentelemetry.io/collector@v0.76.1/otelcol/collector.go:209
go.opentelemetry.io/collector/otelcol.NewCommand.func1
	go.opentelemetry.io/collector@v0.76.1/otelcol/command.go:38
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
main.runInteractive
	github.com/SumoLogic/sumologic-otel-collector/main.go:36
main.run
	github.com/SumoLogic/sumologic-otel-collector/main_others.go:11
main.main
	github.com/SumoLogic/sumologic-otel-collector/main.go:24
runtime.main
	runtime/proc.go:250
2023-08-11T17:27:38.079Z	info	sumologicschemaprocessor@v0.0.0-00010101000000-000000000000/processor.go:98	Processor sumologic_schema has started.	{"kind": "processor", "name": "sumologic_schema", "pipeline": "logs/otlp/containers", "add_cloud_namespace": false, "translate_attributes": true, "translate_telegraf_attributes": true, "nest_attributes": false, "aggregate_attributes": false, "field_attributes": false}
2023-08-11T17:27:38.079Z	info	sumologicexporter@v0.0.0-00010101000000-000000000000/exporter.go:470	setting data urls	{"kind": "exporter", "data_type": "logs", "name": "sumologic/systemd", "logs_url": "SNIP", "metrics_url": "SNIP", "traces_url": ""}
2023-08-11T17:27:38.079Z	info	kube/owner.go:91	Staring K8S resource informers	{"kind": "processor", "name": "k8s_tagger", "pipeline": "logs/otlp/containers", "#infomers": 6}
panic: assertion failed: Page expected to be: 604, but self identifies as 3990861278525940264

goroutine 1 [running]:
go.etcd.io/bbolt._assert(...)
	go.etcd.io/bbolt@v1.3.7/db.go:1359
go.etcd.io/bbolt.(*page).fastCheck(0x7fce095d3000, 0x25c)
	go.etcd.io/bbolt@v1.3.7/page.go:57 +0x1df
go.etcd.io/bbolt.(*Tx).page(0x1000000000008?, 0x7fce0d786cf8?)
	go.etcd.io/bbolt@v1.3.7/tx.go:534 +0x8a
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0x7fce35108108?, {0xc001685040?, 0x1, 0xa}, 0xc00133e9b0)
	go.etcd.io/bbolt@v1.3.7/tx.go:546 +0x65
go.etcd.io/bbolt.(*Tx).forEachPage(...)
	go.etcd.io/bbolt@v1.3.7/tx.go:542
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0017dc540?, 0xc0017dc558?, 0xc00133eb78?, 0xc00133eb48?, {0x73d0258?, 0xb014c60?}, 0xc0012d5b00?)
	go.etcd.io/bbolt@v1.3.7/tx_check.go:83 +0x126
go.etcd.io/bbolt.(*DB).freepages(0x6670bc4?)
	go.etcd.io/bbolt@v1.3.7/db.go:1181 +0x229
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	go.etcd.io/bbolt@v1.3.7/db.go:412 +0xc5
sync.(*Once).doSlow(0xc0018fe1c8?, 0x10?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0018fe000?)
	go.etcd.io/bbolt@v1.3.7/db.go:408 +0x47
go.etcd.io/bbolt.Open({0xc001567880, 0x34}, 0x1?, 0xc00133ee20)
	go.etcd.io/bbolt@v1.3.7/db.go:290 +0x40c
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.newClient(0xc000b9dd50, {0xc001567880?, 0xc00133efb8?}, 0x2540be400, 0xc000918440)
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.76.3/filestorage/client.go:62 +0xaf
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*localFileStorage).GetClient(0xc0015237c0, {0xc000bb7862?, 0xc000bb7988?}, 0xc00133f0a8?, {{0xc000baf6b0?, 0xc00155d590?}, {0xc000baf6ba?, 0xc00133f118?}}, {0x6664f9a, 0x4})
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.76.3/filestorage/extension.go:65 +0x335
go.opentelemetry.io/collector/exporter/exporterhelper.toStorageClient({0x73f22c8, 0xc000126000}, {{0xc00047c610?, 0x0?}, {0x0?, 0x0?}}, {0x73f61c8?, 0xc000b9d420?}, {{0xc000baf6b0, 0x9}, ...}, ...)
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:146 +0x168
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).initializePersistentQueue(0xc000ac3a40, {0x73f22c8, 0xc000126000}, {0x73f61c8?, 0xc000b9d420?})
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:160 +0xe6
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start(0xc000ac3a40, {0x73f22c8?, 0xc000126000?}, {0x73f61c8?, 0xc000b9d420?})
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:200 +0x45
go.opentelemetry.io/collector/exporter/exporterhelper.newBaseExporter.func1({0x73f22c8?, 0xc000126000?}, {0x73f61c8?, 0xc000b9d420?})
	go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/common.go:177 +0xae
go.opentelemetry.io/collector/component.StartFunc.Start(...)
	go.opentelemetry.io/collector/component@v0.76.1/component.go:84
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll(0xc000b61200?, {0x73f22c8, 0xc000126000}, {0x73f61c8, 0xc000b9d420})
	go.opentelemetry.io/collector@v0.76.1/service/internal/graph/graph.go:295 +0xb3
go.opentelemetry.io/collector/service.(*Service).Start(0xc000514580, {0x73f22c8, 0xc000126000})
	go.opentelemetry.io/collector@v0.76.1/service/service.go:138 +0x2a6
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000a25d40, {0x73f22c8, 0xc000126000})
	go.opentelemetry.io/collector@v0.76.1/otelcol/collector.go:184 +0x5eb
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000a25d40, {0x73f22c8, 0xc000126000})
	go.opentelemetry.io/collector@v0.76.1/otelcol/collector.go:209 +0x65
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc000356900, {0x6672460?, 0x1?, 0x1?})
	go.opentelemetry.io/collector@v0.76.1/otelcol/command.go:38 +0x96
github.com/spf13/cobra.(*Command).execute(0xc000356900, {0xc000136010, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000356900)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.runInteractive({{0xc000acd140, 0xc000af8300, 0xc000acd4a0, 0xc000accdb0, 0xc000af8330}, {{0x668dfb3, 0xc}, {0x67bd5bd, 0x2f}, {0x669d731, ...}}, ...})
	github.com/SumoLogic/sumologic-otel-collector/main.go:36 +0x65
main.run(...)
	github.com/SumoLogic/sumologic-otel-collector/main_others.go:11
main.main()
	github.com/SumoLogic/sumologic-otel-collector/main.go:24 +0x1d9
```

**Command used to install/upgrade Collection** Direct command which you used to install/upgrade collection.

Installed using Helm + ArgoCD

**Configuration** Configuration used for Collection e.g. user-values.yaml for helm.

```
sumologic:
  # accessid and accesskey are supplied by the sumo-api-secret Kubernetes Secret
  envFromSecret: sumo-api-secret
  logs:
    enabled: true
    # By default don't collect logs from containers. This allows us
    # to allow users to opt-in via pod annotations.
    container:
      excludeNamespaceRegex: '.*'
    # https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/2843
    # Need to enable multiline logs and ensure that multiline json does not break
    # the otel log ingester.
    multiline:
      enabled: true
      first_line_regex: "(^\\[?\\d{4}-\\d{1,2}-\\d{1,2}.\\d{2}:\\d{2}:\\d{2}|^{$)"
  metrics:
    enabled: false
  traces:
    enabled: false
  # target linux nodes by default
  setup:
    job:
      nodeSelector:
        kubernetes.io/os: linux
otellogs:
  enabled: true
  daemonset:
    priorityClassName: "system-node-critical"
    nodeSelector:
      kubernetes.io/os: linux
    # Allow daemonset to tolerate everything
    tolerations:
      - key: null
        operator: Exists
# controls the sumologic-sumologic-otelcol-logs statefulset
metadata:
  logs:
    autoscaling:
      enabled: true
      maxReplicas: 55
      targetMemoryUtilizationPercentage: 60
      targetCPUUtilizationPercentage: 70
    statefulset:
      priorityClassName: "system-node-critical"
      nodeSelector:
        kubernetes.io/os: linux
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 1Gi
# controls the sumologic-sumologic-otelcol-events statefulset
otelevents:
  statefulset:
    priorityClassName: "system-node-critical"
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"
      ######################### 
      # Disable things we don't want sumologic controlling
      #########################
falco:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux
telegraf-operator:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux
kube-prometheus-stack:
  enabled: false
  alertmanager:
    alertmanagerSpec:
      nodeSelector:
        kubernetes.io/os: linux
metrics-server:
  enabled: false
  nodeSelector:
    kubernetes.io/os: linux
```

**To Reproduce** Steps to reproduce the behavior.

**Expected behavior** A clear and concise description of what you expected to happen.

No crashloop

**Environment (please complete the following information):**

- **Collection version** (e.g. `helm ls -n sumologic`):

3.9.0

- **Kubernetes version** (e.g. `kubectl version`):

1.25

- **Cloud provider**:

AWS/EKS

- **Others**:

**Anything else do we need to know** Add any other context about the problem here, e.g. issue happens only occasionally.

**Comment by swiatekm-sumo** [comment]
Looks like data corruption deep in the persistent queue. Did you experience any other symptoms around it, like issues with the Node disk, the queue being full, and so forth?

These issues are difficult to diagnose without a clear reproduction. I've merged a fix upstream that should help with some of them, and make others easier to understand. It was released in 0.78.0, which means Helm Chart 3.10. Can you upgrade to this and report back if it helps?

**Comment by poblahblahblah** [comment]
No other symptoms noted, no.

I've upgraded to 3.10.0 and we still see the issue:

```
panic: assertion failed: Page expected to be: 604, but self identifies as 3990861278525940264
62
61
goroutine 1 [running]:
60
go.etcd.io/bbolt._assert(...)
59
	go.etcd.io/bbolt@v1.3.7/db.go:1359
58
go.etcd.io/bbolt.(*page).fastCheck(0x7fc5b59d5000, 0x25c)
57
	go.etcd.io/bbolt@v1.3.7/page.go:57 +0x1df
56
go.etcd.io/bbolt.(*Tx).page(0x0?, 0x0?)
55
	go.etcd.io/bbolt@v1.3.7/tx.go:534 +0x8a
54
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0x0?, {0xc000624500?, 0x1, 0xa}, 0xc00183e968)
53
	go.etcd.io/bbolt@v1.3.7/tx.go:546 +0x65
52
go.etcd.io/bbolt.(*Tx).forEachPage(...)
51
	go.etcd.io/bbolt@v1.3.7/tx.go:542
50
go.etcd.io/bbolt.(*Tx).checkBucket(0xc00148cc40, 0xc00148cc58, 0xc00183eb30, 0xc00183eb00, {0x74938a0?, 0xb1a0010}, 0xc0007bdec0)
49
	go.etcd.io/bbolt@v1.3.7/tx_check.go:83 +0x126
48
go.etcd.io/bbolt.(*DB).freepages(0x67ff2bf?)
47
	go.etcd.io/bbolt@v1.3.7/db.go:1181 +0x229
46
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
45
	go.etcd.io/bbolt@v1.3.7/db.go:412 +0xc5
44
sync.(*Once).doSlow(0xc0016ccac8?, 0x10?)
43
	sync/once.go:74 +0xc2
42
sync.(*Once).Do(...)
41
	sync/once.go:65
40
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0016cc900?)
39
	go.etcd.io/bbolt@v1.3.7/db.go:408 +0x47
38
go.etcd.io/bbolt.Open({0xc0016baa00, 0x34}, 0x1?, 0xc00183edd8)
37
	go.etcd.io/bbolt@v1.3.7/db.go:290 +0x40c
36
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.newClient(0xc000e79420, {0xc0016baa00?, 0xc00183ef70?}, 0x2540be400, 0xc00013bb00)
35
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.79.0/filestorage/client.go:51 +0xaf
34
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*localFileStorage).GetClient(0xc001241120, {0x7fc5b60a2cd8?, 0x0?}, 0xc00183f028?, {{0xc0011aefa8?, 0x40?}, {0xc0011aefb2?, 0x3?}}, {0x67f3871, 0x4})
33
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage@v0.79.0/filestorage/extension.go:54 +0x335
32
go.opentelemetry.io/collector/exporter/exporterhelper.toStorageClient({0x74b2ca0, 0xc00007c030}, {{0xc0007a2240?, 0x0?}, {0x0?, 0x0?}}, {0x74b6c10?, 0xc000e78af0?}, {{0xc0011aefa8, 0x9}, ...}, ...)
31
	go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:136 +0x168
30
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).initializePersistentQueue(0xc000a9f7a0, {0x74b2ca0, 0xc00007c030}, {0x74b6c10?, 0xc000e78af0?})
29
	go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:150 +0xe6
28
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start(0xc000a9f7a0, {0x74b2ca0?, 0xc00007c030?}, {0x74b6c10?, 0xc000e78af0?})
27
	go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/queued_retry.go:190 +0x45
26
go.opentelemetry.io/collector/exporter/exporterhelper.newBaseExporter.func1({0x74b2ca0?, 0xc00007c030?}, {0x74b6c10?, 0xc000e78af0?})
25
	go.opentelemetry.io/collector/exporter@v0.79.0/exporterhelper/common.go:166 +0xae
24
go.opentelemetry.io/collector/component.StartFunc.Start(...)
23
	go.opentelemetry.io/collector/component@v0.79.0/component.go:73
22
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll(0xc000558ec0?, {0x74b2ca0, 0xc00007c030}, {0x74b6c10, 0xc000e78af0})
21
	go.opentelemetry.io/collector@v0.79.0/service/internal/graph/graph.go:284 +0xb3
20
go.opentelemetry.io/collector/service.(*Service).Start(0xc000cdc300, {0x74b2ca0, 0xc00007c030})
19
	go.opentelemetry.io/collector@v0.79.0/service/service.go:140 +0x2a6
18
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc0015d2000, {0x74b2ca0, 0xc00007c030})
17
	go.opentelemetry.io/collector@v0.79.0/otelcol/collector.go:173 +0x5cd
16
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0015d2000, {0x74b2ca0, 0xc00007c030})
15
	go.opentelemetry.io/collector@v0.79.0/otelcol/collector.go:198 +0x65
14
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc000005b00, {0x6800b31?, 0x1?, 0x1?})
13
	go.opentelemetry.io/collector@v0.79.0/otelcol/command.go:27 +0x96
12
github.com/spf13/cobra.(*Command).execute(0xc000005b00, {0xc000072050, 0x1, 0x1})
11
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
10
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005b00)
9
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
8
github.com/spf13/cobra.(*Command).Execute(0xc000e4fc80?)
7
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
6
main.runInteractive({{0xc000e4fc80, 0xc0015b0e40, 0xc0015b0000, 0xc000e4f8f0, 0xc0015b0f00}, {{0x681c2b9, 0xc}, {0x69497fd, 0x2f}, {0x682b657, ...}}, ...})
5
	github.com/SumoLogic/sumologic-otel-collector/main.go:36 +0x65
4
main.run(...)
3
	github.com/SumoLogic/sumologic-otel-collector/main_others.go:11
2
main.main()
1
	github.com/SumoLogic/sumologic-otel-collector/main.go:24 +0x1d9
	```

**Comment by poblahblahblah** [comment]
Also seeing this on 3.13.0.

Let me know if you need any other info. If I don't hear back I'll delete the PV so K8s creates a new one and we can get back to a healthy state.

**Comment by swiatekm-sumo** [comment]
Yeah, feel free to delete it, I don't think we'll get anything this way. My hope with the upgrade was more that we'll get some useful log lines if it happens again.

**Comment by Aaron-ML** [comment]
Just a heads up this still happens today on 4.17.0.

```shell
panic: assertion failed: Page expected to be: 87, but self identifies as 509593322935055205

goroutine 1 [running]:
go.etcd.io/bbolt/internal/common.Assert(...)
	go.etcd.io/bbolt@v1.4.2/internal/common/verify.go:65
go.etcd.io/bbolt/internal/common.(*Page).FastCheck(0x7feddc077000, 0x57)
	go.etcd.io/bbolt@v1.4.2/internal/common/page.go:83 +0x1d9
go.etcd.io/bbolt.(*Tx).page(0xc000cfb180?, 0xc00140e0f8?)
	go.etcd.io/bbolt@v1.4.2/tx.go:598 +0x7b
go.etcd.io/bbolt.(*Tx).forEachPageInternal(0xc000000620, {0xc000cfb180, 0x1, 0xa}, 0xc00140e1b0)
	go.etcd.io/bbolt@v1.4.2/tx.go:610 +0x5a
go.etcd.io/bbolt.(*Tx).forEachPage(...)
	go.etcd.io/bbolt@v1.4.2/tx.go:606
go.etcd.io/bbolt.(*Tx).checkInvariantProperties(0xc000000620, 0x57, 0x138ec5c0?, 0xc001b4bb90?, {0xc81e358, 0x1391d800}, 0xc000c316c0)
	go.etcd.io/bbolt@v1.4.2/tx_check.go:143 +0xb2
go.etcd.io/bbolt.(*Tx).recursivelyCheckBucket(0xc000000620, 0xc000000638, 0xc00140e450, 0xc00140e398, {0xc81e358, 0x1391d800}, 0xc000c316c0)
	go.etcd.io/bbolt@v1.4.2/tx_check.go:130 +0x73
go.etcd.io/bbolt.(*DB).freepages(0xc001ae8d88)
	go.etcd.io/bbolt@v1.4.2/db.go:1251 +0x21b
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
	go.etcd.io/bbolt@v1.4.2/db.go:422 +0xc9
sync.(*Once).doSlow(0xc00140e518?, 0xc001ae8d88?)
	sync/once.go:78 +0xab
sync.(*Once).Do(...)
	sync/once.go:69
go.etcd.io/bbolt.(*DB).loadFreelist(0xc001ae8d88?)
	go.etcd.io/bbolt@v1.4.2/db.go:418 +0x3b
go.etcd.io/bbolt.Open({0xc001b54fc0, 0x2d}, 0x180, 0xc000793810)
	go.etcd.io/bbolt@v1.4.2/db.go:299 +0xb48
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.newClient(0xc001b4e900, {0xc001b54fc0, 0x2d}, 0x2540be400, 0xc000ff2e40, 0x1)
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage@v0.130.0/client.go:53 +0x7b
github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage.(*localFileStorage).GetClient(0xc001b4a420, {0x0?, 0x0?}, {{0xb502e85?, 0x0?}}, {{{0xc000f1a7f5?, 0x0?}}, {0x0?, 0x0?}}, {0xb4f183e, ...})
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage@v0.130.0/extension.go:74 +0x6bf
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queue.toStorageClient({0xc87b830, 0x1391d800}, {{{0xc001517ec0, 0xc}}, {0x0, 0x0}}, {0xc7bc5c0?, 0xc001b4b980?}, {{{0xc000f1a7f5, 0x9}}, ...}, ...)
	go.opentelemetry.io/collector/exporter@v0.130.1/exporterhelper/internal/queue/persistent_queue.go:561 +0x113
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queue.(*persistentQueue[...]).Start(0xc9697a0, {0xc87b830, 0x1391d800}, {0xc7bc5c0, 0xc001b4b980?})
	go.opentelemetry.io/collector/exporter@v0.130.1/exporterhelper/internal/queue/persistent_queue.go:117 +0xc5
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queue.(*asyncQueue[...]).Start(0xc828220, {0xc87b830, 0x1391d800?}, {0xc7bc5c0?, 0xc001b4b980?})
	go.opentelemetry.io/collector/exporter@v0.130.1/exporterhelper/internal/queue/async_queue.go:32 +0x49
go.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*QueueBatch).Start(0xc0018b50a0, {0xc87b830, 0x1391d800}, {0xc7bc5c0, 0xc001b4b980})
	go.opentelemetry.io/collector/exporter@v0.130.1/exporterhelper/internal/queuebatch/queue_batch.go:80 +0x8e
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Start(0xc0016d9000?, {0xc87b830?, 0x1391d800?}, {0xc7bc5c0?, 0xc001b4b980?})
	go.opentelemetry.io/collector/exporter@v0.130.1/exporterhelper/internal/base_exporter.go:131 +0xa2
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll(0xc001730f60, {0xc87b830, 0x1391d800}, 0xc00095cf20)
	go.opentelemetry.io/collector/service@v0.130.1/internal/graph/graph.go:431 +0x24b
go.opentelemetry.io/collector/service.(*Service).Start(0xc001727e00, {0xc87b830, 0x1391d800})
	go.opentelemetry.io/collector/service@v0.130.1/service.go:272 +0x2e8
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc001574420, {0xc87b830, 0x1391d800})
	go.opentelemetry.io/collector/otelcol@v0.130.1/collector.go:242 +0xb9d
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc001574420, {0xc87b830, 0x1391d800})
	go.opentelemetry.io/collector/otelcol@v0.130.1/collector.go:312 +0x55
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc00156a908, {0xb4fd7c8?, 0x7?, 0xb4f1a62?})
	go.opentelemetry.io/collector/otelcol@v0.130.1/command.go:39 +0x94
github.com/spf13/cobra.(*Command).execute(0xc00156a908, {0xc0000b23d0, 0x1, 0x1})
	github.com/spf13/cobra@v1.9.1/command.go:1015 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc00156a908)
	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(0xb9afe88?)
	github.com/spf13/cobra@v1.9.1/command.go:1071 +0x13
main.runInteractive({0xb9afe88, {{0xb521b94, 0xc}, {0xb6cb972, 0x2f}, {0xb71496f, 0x37}, {}}, 0x0, {{{0x0, ...}, ...}, ...}, ...})
	github.com/SumoLogic/sumologic-otel-collector/main.go:71 +0x9c
main.run(...)
	github.com/SumoLogic/sumologic-otel-collector/main_others.go:10
main.main()
	github.com/SumoLogic/sumologic-otel-collector/main.go:57 +0x498
```

**Comment by mlushpenko** [comment]
We hit this on chart 4.21.1 / otelcol 0.145.0-sumo-0 (bbolt 1.4.3) in production yesterday, and I think we have the reproduction that was missing in 2023. Posting the full chain in case it's useful, and asking whether this can be reopened.

**What happened**

One pod of the logs metadata StatefulSet (`sumologic-otelcol-logs-3`) went into CrashLoopBackOff and stayed there for 4h11m across 54 restarts:

```
panic: assertion failed: Page expected to be: 23679, but self identifies as 0
go.etcd.io/bbolt/internal/common.(*Page).FastCheck
...
filestorage.newClient(..., 0x2540be400, ..., 0x1)
filestorage.(*localFileStorage).createClientWithPanicRecovery
queue.(*persistentQueue[...]).Start
```

**Trigger**

The HPA scaled the StatefulSet 4→3 at 15:31 ("All metrics below target") and back 3→4 at 15:33 (`lastScaleTime: 15:33:17Z`). The logs StatefulSet runs with `terminationGracePeriodSeconds: 30` and no `preStop` hook, so a 10k-deep persistent queue gets SIGKILLed mid-commit. The PVC is reattached rather than recreated, so the damaged file returns on every restart.

**Why it never recovers — two defaults compounding**

1. `filestorage` opens bbolt with `NoSync: true`, because `noSync = !cfg.FSync` and `fsync` defaults to false. That's the literal `0x1` argument in the stack above. Without fsync barriers the kernel is free to reorder writeback, so an ungraceful kill can leave the meta page referencing pages that never landed — which is exactly the `FastCheck` assertion.

2. The extension has a recovery path for precisely this, but `createClientWithPanicRecovery` returns early before installing the `defer/recover` when `cfg.Recreate` is false — also the default. So the panic escapes and kills the process, every restart, indefinitely.

The chart sets neither. `conf/logs/otelcol/config.yaml:102` renders only `directory`, `timeout`, and `compaction`, and grepping 4.21.1 for `fsync` or `recreate` finds nothing relevant.

**Mitigation, which also confirms the mechanism**

Since the chart exposes no knob, we injected both through `metadata.logs.config.merge`:

```yaml
metadata:
  logs:
    config:
      merge:
        extensions:
          file_storage:
            fsync: true
            recreate: true
```

On the next roll, the same corrupt file on the same PVC produced this instead of a panic:

```
20:03:05.631 warn  filestorage@v0.145.0/extension.go:119  Database corruption detected, recreating database file
  file:  /var/lib/storage/otc/exporter_sumologic__logs
  panic: assertion failed: Page expected to be: 23679, but self identifies as 0
20:03:05.631 info  filestorage@v0.145.0/extension.go:131  Corrupted database file renamed
  original: /var/lib/storage/otc/exporter_sumologic__logs
  backup:   /var/lib/storage/otc/exporter_sumologic__logs.2026-08-03T20:03:05.631.backup
20:03:05.646 info  Everything is ready. Begin running and processing data.
```

Same page number as all 54 crashes. Serving 15 ms later, repaired in place, no PVC surgery needed.

In fairness: we enable the HPA ourselves (`metadata.logs.autoscaling.enabled: true`, `maxReplicas: 50`) and it is off by default in the chart. But the chart does support autoscaling a StatefulSet whose pods each own a persistent bbolt queue, and the storage extension isn't configured to survive that combination. The original 2023 report here also ran `autoscaling.enabled: true, maxReplicas: 55`, and the 4.17.0 report above is a third org.

**Asks**

1. Expose `fsync` and `recreate` as chart values for the `file_storage` extension. `config.merge` works, but it's an unvalidated overwrite onto rendered YAML — if that block moves or is renamed in a future chart, our override silently becomes a no-op and we find out via the next crashloop.
2. Consider defaulting `recreate: true`. There's a real tradeoff, since it discards up to `queue_size` records. For a log shipper we'd take that over a permanent CrashLoopBackOff, but that's your call to make.
3. Consider a `preStop` hook or a longer `terminationGracePeriodSeconds` for the logs metadata StatefulSet. That's the actual prevention — there's currently no `preStop` and no grace-period override anywhere under `templates/logs/`.

One observation relevant to ask 3 above: the chart already ships `pvc-cleaner`, which takes the HPA name and skips any PVC whose ordinal is below `max(currentReplicas, desiredReplicas)`, and only deletes unmounted ones. So index 3 with 4 replicas is permanently exempt from cleanup. The tooling addresses the leftover-PVC symptom, but the file inside the retained PVC is what kills the pod.

Happy to test a chart build with these exposed if that helps.

**Comment by dhruv-shah-sumo** [comment]
Hello @mlushpenko thanks a lot for reporting the issue and for the detailed explanation. I am summarizing the ask below, can you please confirm if we are on the same page:

```
- fsync: true — During normal operation. Each individual write is atomic on disk — even SIGKILL can only lose one transaction.  
- recreate: true — At startup after corruption. Recovers from damage that already happened.
- preStop / longer grace period — At shutdown. Gives enough time so SIGKILL never arrives mid-write.
```

Your current implementation which uses config.merge option is the recommended way to use additional configs which are not exposed by the chart and we do not plan to remove that option anytime soon. 

Once the above mentioned details are confirmed, we will investigate it internally and get back to you.

**Comment by mlushpenko** [comment]
Yep, that's it — same page. Two tiny notes:

`recreate: true` catches the *panic* kind of corruption, which is exactly what we hit. bbolt returns some other corruption as plain errors (`ErrInvalid`, `ErrChecksum`) that don't trigger the recreate path, so it's not a catch-all — worth knowing if you weigh it as a default. `fsync` mapping to `NoSync` is spot on, that write ordering is what stops the mid-write SIGKILL from wrecking the file.

Good to hear `config.merge` is the recommended path and sticking around — that was our main worry. Only reason we'd still like `fsync`/`recreate` as real chart values: the merge silently no-ops if that config block ever gets renamed, so we'd find out from the next crashloop rather than at upgrade time. Not urgent, the merge works.

One for the investigation: three collectors use `file_storage` as a durable queue (`sumologic-otelcol-logs`, `otelevents`, `otelcol-logs-collector`) — we've only patched the first, so worth covering all three if you expose the values.

Happy to test a build. And could you reopen this while it's being looked at?

**Comment by dhruv-shah-sumo** [comment]
ACK @mlushpenko Just wanted to gather some information. 
- What type of storageClass are you using in your deployment? 
- What is the size of storage that you have attached for persistence queueing?
- The comment mentions that you're using 4.21.1, is that still correct or have you upgraded to any other version? 

I have opened the issue.

**Comment by mlushpenko** [comment]
Thanks for reopening.

- **storageClass**: `ebs-csi-gp3`, our cluster default. Plain gp3, nothing custom: `type: gp3`, `encrypted: true`, `allowVolumeExpansion: true`, default reclaim (Delete) and Immediate binding. No provisioned IOPS or throughput, so it sits at the gp3 baseline of 3000 IOPS / 125 MiB/s.
- **size**: 20Gi per logs-metadata PVC, same in prod and nonprod.
- **version**: still 4.21.1, no upgrade since.
- **nodes**: Bottlerocket OS, containerd runtime. Mentioning for completeness, though I don't think it's the storage factor. The corruption is at the bbolt layer (the extension opens the DB with `NoSync` so nothing ever gets fsync'd), which is filesystem and OS agnostic. It'd corrupt the same way on any host after an ungraceful kill.

So nothing exotic on the storage side. Standard encrypted gp3 on Bottlerocket.

**Comment by dhruv-shah-sumo** [comment]
Hi @mlushpenko We have released https://github.com/SumoLogic/sumologic-kubernetes-collection/releases#release-v4.21.2 with `fsync, recreate, terminationGracePeriodSeconds` configuration. 

On a side note: 
- This is a patch release on version 4.21.1 and we will be releasing it on the 5.4.0 or later releases so if you upgrade to any version < 5.4.0, these configs will not be available. If for any reason, you need to upgrade to version < 5.4.0, I recommend using config.merge option which you're using right now. 
- fsync helps us with the durability but it also compromises the performance of OTEL collector as it tries to sync queue entry to disk before processing the next one in the queue. I recommend monitoring CPU/memory once you enable these config. If they are staying above 60% constantly, you may want to increase them to accommodate any sudden surge in the data ingestion.

**Comment by mlushpenko** [comment]
Perfect, that covers it. So we stay on config.merge until 5.4.0, then move to the native values once we're on 5.4.0+. And good call on the fsync cost, we'll watch CPU/mem now that it's syncing every queue entry and bump limits if it creeps up. Thanks a lot for the quick turnaround.

**Comment by dhruv-shah-sumo** [comment]
https://github.com/SumoLogic/sumologic-kubernetes-collection/releases/tag/v5.4.0 We have released the config keys in 5.4.0
